# Generated by Django 3.2.4 on 2021-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_nuevo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevo',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
