# Generated by Django 3.2.4 on 2021-07-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_nuevo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevo',
            name='descri',
            field=models.CharField(max_length=1000),
        ),
    ]
