# Generated by Django 3.2.4 on 2021-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_nuevo_descri'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('lista_producto', models.CharField(max_length=30)),
                ('total_carrito', models.CharField(max_length=30)),
            ],
        ),
    ]
